#!/bin/bash
# Script Modified By-Arisabdulaziz
clear
echo "----Selamat Datang di Script Menu Termux---"|lolcat
echo "---------Created By. Arisabdulaziz---------"|lolcat
date | lolcat
echo "-------------------------------------------"| lolcat
echo ""
echo  "Daftar Menu;"| lolcat
echo ""
echo ""
echo  "1.Bot Kubik" |lolcat
echo  "2.Bot Facebook"| lolcat
echo  "3.Bot Instagram"| lolcat
echo  "4.Yt Converter"| lolcat
echo  "5.Sunda Translator"| lolcat
echo  "6.Info Cuaca"| lolcat
echo  "7.Ddos Script"| lolcat
echo  "8.Deface Web"| lolcat
echo  ""
echo  "--------------------------------------------"| lolcat
read -p "Tulis Pilihan Anda (angka):" x
if [ $x -eq 1 ];
then
clear
echo "Sedang Diproses............"|lolcat
./bot-kubik;
fi
if [ $x -eq 2 ];
then
clear
echo "Sedang Diproses............"|lolcat
./bot-fb;
fi
if [ $x -eq 3 ];
then
clear:
echo "Sedang Diproses............"|lolcat
./bot-ig;
fi
if [ $x -eq 4 ];
clear
echo "Sedang Diproses............"|lolcat
./yt-convert;
fi
if [ $x -eq 5 ];
then
clear
echo "Sedang Diproses............"|lolcat
./sunda-translate;
fi
if [ $x -eq 6 ];
then
clear
echo "Sedang Diproses............"|lolcat
./info-cuaca;
fi
if [ $x -eq 7 ];
then
clear
echo "Sedang Diproses............"|lolcat
./ddos-script;
fi
if [ $x -eq 8 ];
then
clear
echo "Sedang Diproses............"|lolcat
./deface;
fi
